---
- hosts: etl_docker 
  tasks:
          - name: Stop LP-ETL
            docker_compose:
                    project_src: /opt/lp/etl-docker
                    state: absent
                    remove_images: all
          - name: Remove images
            shell: docker image rm $(docker images --filter "label=lp_project=etl" -q)
          - name: Build and start LP-ETL # this will work, but ansible will fail due to https://github.com/ansible/ansible/issues/42506
            environment:
                    LP_ETL_PORT: 8090
            docker_compose:
                    project_src: /opt/lp/etl-docker
                    state: present
                    build: yes
                    debug: yes
